services:
  frontend:
    container_name: pedidofacil_frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file: .env
    networks:
      - pedidofacil_default
    restart: unless-stopped

networks:
  pedidofacil_default:
    external: true
